<?php echo $this->doctype() ?>
<html>
<head>
	<?php echo $this->headTitle() ?>
	<?php echo $this->headMeta() ?>
	<?php echo $this->headLink() ?>
	<?php echo $this->headStyle() ?>
	<?php echo $this->dojo() ?>
	<?php echo $this->headScript() ?>
</head>
<body>
	<div class="lsLayout" dojoType="dijit.layout.BorderContainer" gutters="false">
		<div class="lsLayoutHeader" dojoType="dijit.layout.ContentPane" region="top" parseOnLoad="false">
			<div dojoType="limesoft.Header"></div>
		</div>
		<div class="lsLayoutContent" dojoType="dijit.layout.ContentPane" region="center" parseOnLoad="false">
			<div dojoType="limesoft.Content"><?php echo $this->layout()->content ?></div>
		</div>
		<div class="lsLayoutFooter" dojoType="dijit.layout.ContentPane" region="bottom" parseOnLoad="false">
			<div dojoType="limesoft.Footer"></div>
		</div>
	</div>
</body>
</html>
