<?php echo $this->doctype() ?>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Test</title>
    <?php	
    if($this->jQuery()->isEnabled()){
		$this->jQuery()->setLocalPath($this->baseUrl('/scripts/jquery-1.4.2.min.js'));
		echo $this->jQuery();
	}
	
	?>
	<?php echo $this->headScript() ?>
	<?php echo $this->headLink() ?>
</head>
<body>
	<?php echo $this->layout()->content ?>
</body>
</html>